import { icon } from '../../utils'

export const applicationIcons = {
  'arrow-down': icon('ArrowDown', () => import('./ArrowDownIcon')),
  'arrow-left': icon('ArrowLeft', () => import('./ArrowLeftIcon')),
  'arrow-right': icon('ArrowRight', () => import('./ArrowRightIcon')),
  'arrow-right-2': icon('ArrowRightIcon2', () => import('./ArrowRightIcon2')),
  'arrow-right-3': icon('ArrowRightIcon3', () => import('./ArrowRightIcon3')),
  'arrow-up-right': icon('ArrowUpRight', () => import('./ArrowUpRightIcon')),
  'brand-logo': icon('BrandLogo', () => import('./BrandLogo')),
  'brand-logomark': icon('BrandLogomark', () => import('./BrandLogomark')),
  calendar: icon('Calendar', () => import('./CalendarIcon')),
  'charts-line': icon('ChartsLine', () => import('./ChartsLineIcon')),
  check: icon('Check', () => import('./CheckIcon')),
  'chevron-down': icon('ChevronDown', () => import('./ChevronDownIcon')),
  'chevron-left': icon('ChevronLeft', () => import('./ChevronLeftIcon')),
  'chevron-right': icon('ChevronRight', () => import('./ChevronRightIcon')),
  'chevron-up': icon('ChevronUp', () => import('./ChevronUpIcon')),
  'colored-bond': icon('ColoredBond', () => import('./ColoredBond')),
  'colored-legal': icon('ColoredLegal', () => import('./ColoredLegal')),
  'colored-liquidity': icon('ColoredLiquiditity', () => import('./ColoredLiquiditity')),
  'colored-stake': icon('ColoredStake', () => import('./ColoredStake')),
  'colored-trade': icon('ColoredTrade', () => import('./ColoredTrade')),
  copy: icon('Copy', () => import('./CopyIcon')),
  cross: icon('Cross', () => import('./CrossIcon')),
  cup: icon('Cup', () => import('./Cup')),
  'dark-theme': icon('DarkTheme', () => import('./DarkThemeIcon')),
  docs: icon('Docs', () => import('./DocsIcon')),
  'docs-outlined': icon('DocsOutlined', () => import('./DocsOutlinedIcon')),
  donation: icon('Donation', () => import('./Donation')),
  dots: icon('Dots', () => import('./DotsIcon')),
  energy: icon('Energy', () => import('./EnergyIcon')),
  'exclamation-circle': icon('ExclamationCircle', () => import('./ExclamationCircle')),
  'exclamation-triangle': icon('ExclamationTriangle', () => import('./ExclamationTriangle')),
  eye: icon('Eye', () => import('./EyeIcon')),
  'eye-slash': icon('EyeSlash', () => import('./EyeSlashIcon')),
  growth: icon('Growth', () => import('./GrowthIcon')),
  'govern-outlined': icon('GovernOutlined', () => import('./GovernOutlinedIcon')),
  history: icon('History', () => import('./HistoryIcon')),
  home: icon('Home', () => import('./HomeIcon')),
  info: icon('Info', () => import('./InfoIcon')),
  'info-outlined': icon('InfoOutlined', () => import('./InfoOutlinedIcon')),
  language: icon('Language', () => import('./LanguageIcon')),
  legal: icon('Legal', () => import('./LegalIcon')),
  'light-theme': icon('LightTheme', () => import('./LightThemeIcon')),
  logo: icon('Logo', () => import('./LogoIcon')),
  long: icon('Long', () => import('./LongIcon')),
  lockIcon: icon('Lock', () => import('./LockIcon')),
  minus: icon('Minus', () => import('./MinusIcon')),
  'money-bag': icon('MoneyBag', () => import('./MoneyBagIcon')),
  percent: icon('Percent', () => import('./PercentIcon')),
  plus: icon('Plus', () => import('./PlusIcon')),
  portfolio: icon('Portfolio', () => import('./PortfolioIcon')),
  'ppo-logo': icon('PpoLogo', () => import('./PpoLogoIcon')),
  power: icon('Power', () => import('./PowerIcon')),
  prepo: icon('Prepo', () => import('./PrepoIcon')),
  priest: icon('Priest', () => import('./Priest')),
  profile: icon('Profile', () => import('./ProfileIcon')),
  search: icon('Search', () => import('./SearchIcon')),
  share: icon('Share', () => import('./ShareIcon')),
  'shopping-cart-arrow-down': icon(
    'ShoppingCartArrowDown',
    () => import('./ShoppingCartArrowDownIcon')
  ),
  'shopping-cart-arrow-right': icon(
    'ShoppingCartArrowRight',
    () => import('./ShoppingCartArrowRightIcon')
  ),
  short: icon('Short', () => import('./ShortIcon')),
  settings: icon('Settings', () => import('./SettingsIcon')),
  'sort-down': icon('SortDown', () => import('./SortDownIcon')),
  stake: icon('Stake', () => import('./StakeIcon')),
  'trading-volume': icon('TradingVolume', () => import('./TradingVolume')),
  'trading-liquidity': icon('TradingLiquidity', () => import('./TradingLiquidity')),
  'water-drop': icon('WaterDrop', () => import('./WaterDropIcon')),
  reset: icon('Reset', () => import('./ResetIcon')),
  'zoom-in-two': icon('ZoomInIconTwo', () => import('./ZoomInIconTwo')),
  'zoom-out-two': icon('ZoomOutIconTwo', () => import('./ZoomOutIconTwo')),
}
