[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', '../../../lib']
allow_paths = ['node_modules', '../../../']
remappings = ['@prepo-shared-contracts=./node_modules/@prepo-shared-contracts']
test = 'test'
cache_path  = 'cache_forge'
